#pragma config(Sensor, dgtl1,  n_Meter,        sensorSONAR_cm)
#pragma config(Sensor, dgtl3,  e_Meter,        sensorSONAR_cm)
#pragma config(Sensor, dgtl5,  s_Meter,        sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  w_Meter,        sensorSONAR_cm)
#pragma config(Motor,  port1,           x_Motor,       tmotorVex269_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           y_Motor,       tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//---Constants
int NOMINAL_SPEED = 50; //Regular forward motor motion
int NOMINAL_DURATION = 750; //Time, in milliseconds, that nominal forward motion is sustained for
int cm_threshold = 10; //To be considered a wall, Ultrasonic values must be within this range

void move(int cardinal) //Moves one unit in the target direction
{
	clearTimer(T1);
	int c_x = 1; //Used to determine direction of motion
	int c_y = 1; //^
	switch (cardinal)
	{
		case 0:
			c_x = 0;
			c_y = 1;
		break;
		case 1:
			c_x = 1;
			c_y = 0;
		break;
		case 2:
			c_x = 0;
			c_y = -1;
		break;
		case 3:
			c_x = -1;
			c_y = 0;
		break;
	}
	while (time1[T1] <= NOMINAL_DURATION)
	{
		motor[x_Motor] = c_x * NOMINAL_SPEED;
		motor[y_Motor] = c_y * NOMINAL_SPEED;
	}
	motor[x_Motor] = 0;
	motor[y_Motor] = 0;
}


task main()
{
	bool prev = false;
	while (true)
	{
		if (vexRT[Btn8U] == 1)
		{
			if (prev == false)
			{
				prev = true;
				move(0);
			}
		}
		else if (vexRT[Btn8R] == 1)
		{
			if (prev == false)
			{
				prev = true;
				move(1);
			}
		}
		else if (vexRT[Btn8D] == 1)
		{
			if (prev == false)
			{
				prev = true;
				move(2);
			}
		}
		else if (vexRT[Btn8L] == 1)
		{
			if (prev == false)
			{
				prev = true;
				move(3);
			}
		}
		else //No pressed buttons
		{
			prev = false;
		}
	}
}

int* grabOpen()
{
	int openCardinals[4] = {5, 5, 5, 5};
	return openCardinals;
}
