#pragma config(Motor,  port1,           one,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           two,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           three,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           four,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           five,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          ten,           tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
	{

		motor[two] = vexRT[Ch2];
		motor[four] = vexRT[Ch2];
		motor[five] = vexRT[Ch2];
		motor[three] = vexRT[Ch2];
	}
}
